spring:
  application:
    name: flight-search-be

amadeus:
  api:
    client-id: ${AMADEUS_API_CLIENT_ID}
    client-secret: ${AMADEUS_API_CLIENT_SECRET}
    token-url: https://test.api.amadeus.com/v1/security/oauth2/token
    flight-search-url: https://test.api.amadeus.com/v2/shopping/flight-offers
    search-airports-url: https://test.api.amadeus.com/v1/reference-data/locations