services:
  backend:
    build:
      context: ./flight-search-be
      dockerfile: Dockerfile.dev
    volumes:
      - ./flight-search-be:/app
    ports:
      - 8080:8080
    environment:
      - AMADEUS_API_CLIENT_ID=${AMADEUS_API_CLIENT_ID}
      - AMADEUS_API_CLIENT_SECRET=${AMADEUS_API_CLIENT_SECRET}
    command: ./gradlew bootRun

  frontend:
    build:
      context: ./flight-search-fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./flight-search-fe:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

